name: form
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  dio: ^5.9.0
  
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_pdfview: ^1.4.3
  flutter_riverpod: ^3.0.1
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^9.0.0
  font_awesome_flutter: ^10.10.0
  formz: ^0.8.0
  geolocator: ^14.0.2
  go_router: ^16.2.4
  google_maps_flutter: ^2.13.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  lottie: ^3.3.2
  mime: ^2.0.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  share_plus: ^12.0.0
  syncfusion_flutter_charts: ^31.2.5
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
